name: Upload requirements.txt as Release Asset

on:
  workflow_dispatch:   # Run manually from GitHub UI

permissions:
  contents: write   # needed for release upload

jobs:
  upload-requirements:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV

      - name: Create or update release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: requirements-${{ env.date }}
          name: "Requirements release ${{ env.date }}"
          body: "Automated release of requirements.txt"
          files: src/requirements.txt   # adjust path if needed
