site_name: ML Assist docs
theme:
  name: material

markdown_extensions:
  - admonition

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Tutorials: 
    - Overview: tutorials/overview.md
    - Feature 1: tutorials/feature1.md
  - User Guide:
    - FAQ: user-guide/faq.md
    - Installation: user-guide/installing.md
    - UI Overview: user-guide/ui-overview.md
  - Developer Guide:
    - Architecture: developer-guide/architecture.md
    - Contributing: developer-guide/contributing.md
    - Modules:
      - ApiWindow: developer-guide/modules/ApiWindow.md
      - AppLogger: developer-guide/modules/AppLogger.md
      - BuildingDetection: developer-guide/modules/BuildingDetection.md
      - BuildingDetectionWindow: developer-guide/modules/BuildingDetectionWindow.md
      - Classification: developer-guide/modules/Classification.md
      - config_: developer-guide/modules/config_.md
      - CropStreetWindow: developer-guide/modules/CropStreetWindow.md
      - Duplicates_Better: developer-guide/modules/Duplicates_Better.md
      - geoscatter: developer-guide/modules/geoscatter.md
      - image_metadata_area_scan: developer-guide/modules/image_metadata_area_scan.md
      - main_app: developer-guide/modules/main_app.md
      - map_index_maker: developer-guide/modules/map_index_maker.md
      - Metadata_scanner_grid_search: developer-guide/modules/Metadata_scanner_grid_search.md
      - model_download: developer-guide/modules/model_download.md
      - model_training: developer-guide/modules/model_training.md
      - Tile_Downloader: developer-guide/modules/Tile_Downloader.md
      - utils: developer-guide/modules/utils.md

