name: Test Models ZIP

on:
  workflow_dispatch: # manual trigger
  release:
    types: [published, edited]  # runs when you update/publish a release

jobs:
  validate-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Download latest release asset
        uses: robinraju/release-downloader@v1
        with:
          repository: ${{ github.repository }}
          latest: true
          fileName: "models.zip"

      - name: Extract models.zip
        run: |
          mkdir extracted
          unzip models.zip -d extracted

      - name: Validate structure
        run: |
          echo "Checking subfolders..."
          if [ $(find extracted -mindepth 1 -type d | wc -l) -eq 0 ]; then
            echo "❌ No subfolders found in models.zip!"
            exit 1
          fi

          echo "Checking duplicate filenames across folders..."
          allfiles=$(find extracted -type f -printf "%f\n")
          dupes=$(echo "$allfiles" | sort | uniq -d)
          if [ ! -z "$dupes" ]; then
            echo "❌ Duplicate file names found across folders:"
            echo "$dupes"
            exit 1
          fi

          echo "✅ models.zip passed structure checks."